// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication_API.Data;

#nullable disable

namespace WebApplication_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230724070927_CreateNewTableWithHotelNumbers")]
    partial class CreateNewTableWithHotelNumbers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication_API.Model.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 7, 24, 10, 9, 27, 447, DateTimeKind.Local).AddTicks(3776),
                            Description = "Luxury hotel in Te Aro with indoor pool and restaurant",
                            ImageUrl = "https://images.trvl-media.com/lodging/2000000/1380000/1376400/1376357/b26bd2e2.jpg?impolicy=resizecrop&rw=1200&ra=fit",
                            Name = "QT Wellington",
                            Rate = 100.0,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 7, 24, 10, 9, 27, 447, DateTimeKind.Local).AddTicks(3824),
                            Description = "Hotel description",
                            ImageUrl = "https://images.trvl-media.com/lodging/1000000/980000/977400/977353/ba82cfaa.jpg?impolicy=resizecrop&rw=1200&ra=fit",
                            Name = "Naumi Studio Wellington",
                            Rate = 175.0,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 7, 24, 10, 9, 27, 447, DateTimeKind.Local).AddTicks(3826),
                            Description = "Suburban hotel with outdoor pool, near Villa Maria Auckland Winery",
                            ImageUrl = "https://images.trvl-media.com/lodging/11000000/10070000/10062500/10062481/f07817e8.jpg?impolicy=resizecrop&rw=1200&ra=fit",
                            Name = "Naumi Auckland Airport",
                            Rate = 200.0,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 7, 24, 10, 9, 27, 447, DateTimeKind.Local).AddTicks(3829),
                            Description = "Wellington upmarket aparthotel with 24-hour fitness",
                            ImageUrl = "https://images.trvl-media.com/lodging/67000000/66530000/66522700/66522603/fdaeade6.jpg?impolicy=resizecrop&rw=1200&ra=fit",
                            Name = "Ramada by Wyndham Wellington Taranaki Street",
                            Rate = 150.0,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 7, 24, 10, 9, 27, 447, DateTimeKind.Local).AddTicks(3831),
                            Description = "Luxury hotel with spa, near Sky Tower",
                            ImageUrl = "https://images.trvl-media.com/lodging/2000000/1390000/1386200/1386172/e654fdfb.jpg?impolicy=resizecrop&rw=1200&ra=fit",
                            Name = "The Grand by SkyCity",
                            Rate = 250.0,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 7, 24, 10, 9, 27, 447, DateTimeKind.Local).AddTicks(3834),
                            Description = "Luxury hotel with restaurant, near Princes Warf Visitor Information Centre",
                            ImageUrl = "https://images.trvl-media.com/lodging/1000000/10000/5500/5465/d4144184.jpg?impolicy=resizecrop&rw=1200&ra=fit",
                            Name = "M Social Auckland",
                            Rate = 130.0,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebApplication_API.Models.HotelNumber", b =>
                {
                    b.Property<int>("HotelNum")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("HotelNum");

                    b.ToTable("HotelNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
